openapi: 3.1.1
info:
  title: Llamatik API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
  - url: http://api.llamatik.com/v1
    description: Lightweight llama.cpp HTTP server
paths:
  /embeddings:
    get:
      summary: Returns a list of embeddings.
      description: Returns a list of embeddings.
      responses:
        '200': # status code
          description: A list of embeddings.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /generation:
    get:
      summary: Returns generated string.
      description: Returns generated string.
      responses:
        '200': # status code
          description: Generated string.
          content:
            application/json:
              schema:
                type: string
                items:
                  type: string
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: [ ]